amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.access_key_id%>
  secret_access_key: <%= Rails.application.credentials.secret_access_key%>
  region: <%= Rails.application.credentials.region%>
  bucket: <%= Rails.application.credentials.bucket_name%>

local:
  root: <%= Rails.root.join("storage") %>
  service: Disk
test:
  root: <%= Rails.root.join("tmp/storage") %>
  service: Disk
