amazon:
  service: S3
  access_key_id: AKIAIGAGQQY5MJCSPQZA
  secret_access_key: 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
  region: sa-east-1
  bucket: desafio-zimobi-2019

local:
  root: <%= Rails.root.join("storage") %>
  service: Disk
test:
  root: <%= Rails.root.join("tmp/storage") %>
  service: Disk
